# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef0c11a2d2768f7ba6e95a034c1af19f30a23d739e85b947bcb9895004ecb86f695071d923b565b9c4e85b3123095e5b48c965ddeecc2bf87290d664960cb37

test:
  secret_key_base: 161ce8133429a5d2f6b1e777f039e03eecb0cc247e97bee56ecd34f96ee664a077eeb491fb6c33c277ea335a8252a2ed9b4c0f31e438025e8dd20c0f67110f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
